name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  # Run everything on main, most-recent on PR builds
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Install dev-requirements
        run: |
          apt-get update
          apt-get install -y git
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt --no-cache-dir
        shell: bash
      - name: Run CI
        run: ./dev ci
        shell: bash
      - name: Run pytest
        run: pytest --cov topology_toolbox tests
      # - name: Publish docs
      #   if: ${{github.ref == 'refs/heads/main'}}
      #   uses: Cecilapp/GitHub-Pages-deploy@3.2.1
      #   env: { GITHUB_TOKEN: "${{ github.token }}" }
      #   with:
      #     build_dir: docs/build/html/
